42 partners initial load
matthew-r-clark/drm pull request #43
Opened 2021-10-03 20:54 UTC by matthew-r-clark

closes #42 

- Changed API route for getting partners to return all instead of paginate results. Will need to handling pagination in client; left pagination code commented in API file for reference.
- Commented out the `Partners` component on root `index.js` page because it no longer works with API changes.

2021-10-03 22:48 UTC, matthew-r-clark commented
I'm going to go ahead and do the same thing with ministers API route in this PR.

2021-10-04 01:53 UTC, Jon-D-Smith commented on src/pages/api/ministers/index.js
> -    if (data && isEmpty(data)) {
We can get rid of the isEmpty and omit imports since they are no longer being used.

2021-10-04 01:55 UTC, Jon-D-Smith requested changes

2021-10-04 01:55 UTC, Jon-D-Smith commented on src/pages/api/partners/index.js
> -    const query = omit(['limit', 'page'], req.query);
We can get rid of them on this file as well.

2021-10-12 01:55 UTC, Jon-D-Smith approved these changes

2021-10-12 01:55 UTC, merged